Add basic issue templates
bonlineza/.github pull request #2
Opened 2019-06-09 17:53 UTC by robguy21

This should lay the ground work for future iterations on templates for bug reports and feature requests

2019-06-10 08:03 UTC, willemwe0 approved these changes

2019-06-11 09:49 UTC, countnoobula requested changes

2019-06-11 09:49 UTC, countnoobula commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I think these should be _italics_ like we have them on Allianz, as this differentiates between the user input and template design.

That would mean it would look like:

--- 

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

2019-06-11 10:29 UTC, adameier commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Critical - _This impacts a critical procedure_
Does an issue have to be only one of these? because then I'm not sure what the distinction between Urgent and Critical is

2019-06-11 11:06 UTC, countnoobula commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Critical - _This impacts a critical procedure_
I think Urgent is user visible, where as critical is a background process.

Urgent - It interrupts the user flow.
Critical - It interrupts sync or background tasks (such as sending mails, or syncing data?).

@robguy21 can you confirm?

2019-06-12 22:30 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Critical - _This impacts a critical procedure_
Correct, I wanted to differentiate between "this is breaking for users" and "this is breaking non-user-facing functionality".

For example - the queues not being able to run versus "add a payment" resulting in broken page [luxity]

2019-07-03 08:44 UTC, willemwe0 submitted a review, later dismissed

2019-07-03 08:54 UTC, sscholle requested changes

2019-07-03 08:54 UTC, sscholle commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Critical - _This impacts a critical procedure_
`critical procedure` is somewhat vague and can be confused, as user interactions can be critical procedures too....

2019-07-03 08:54 UTC, sscholle commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Any other comments? (logs, output, error reports, or any other useful information)
Extra Notes - i think is a clear enough description, no need for a long list of examples

2019-07-03 08:57 UTC, pruhesi commented on .github/ISSUE_TEMPLATE/bug_report.md
> +(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)
link above?

2019-07-03 08:59 UTC, pruhesi commented
@robguy21 @countnoobula Just an inquiry about whether issues created by devs would need to follow the above format?

2019-07-03 09:07 UTC, robguy21 commented
@pruhesi yes- if a developer is making a feature request or a bug report

2019-07-03 09:46 UTC, adameier commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Critical - _This impacts a critical procedure_
perhaps a distinction between a bug being user-facing or not, as well as it being critical or not. And a combination of the two can be selected.
e.g. a bug can be user-facing and be either critical or not, the same goes for a bug that isnt user-facing.

2019-08-21 13:25 UTC, willemwe0 submitted a review, later dismissed

2019-08-21 15:17 UTC, willemwe0 submitted a review, later dismissed

2019-08-22 07:28 UTC, sscholle commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Normal - _tackle important issues before attending to this this_
this this

2019-08-22 07:28 UTC, sscholle commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Extreme - _The bug is breaking interactions for users, meaning that they are unable to use the system_
extreme and urgent seem to be the same - maybe have this level take high priority meaning it goes to top of todo list. - something that is critical goes here
High - means what it says - good - usually a style/UX/ or bug fix that can have impact in the experience
Normal - add it to the bottom - usually a minor tweak and new feature requests

2019-08-22 07:28 UTC, sscholle commented on .github/ISSUE_TEMPLATE/feature_request.md
> +_A clear and concise description of any alternative solutions or features you've considered._
i'd image `clear and concise` is assumed as we have so many headings to fill information under - so probably no need for that much repetition

2019-09-05 14:46 UTC, pruhesi submitted a review, later dismissed

2019-09-06 09:03 UTC, countnoobula submitted a review, later dismissed

2019-09-06 13:23 UTC, sscholle requested changes

2019-09-06 13:23 UTC, sscholle commented on .github/ISSUE_TEMPLATE/bug_report.md
> +- [ ] Impacts the system critically - _The system is unable to perform tasks, but these tasks are not critical_
confusing: `critically` and `not critical` - which one is it?

2019-09-06 13:28 UTC, sscholle submitted a review, later dismissed

2019-09-06 13:28 UTC, willemwe0 requested changes

2019-09-06 13:28 UTC, willemwe0 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +## Description of Existing Problem
A good requirement or user story describes the problem, not a solution.

https://medium.com/101ideasforagileteams/problem-centric-user-stories-9815ba23e132

Therefore I think we can leave this out and make the bottom one:
> User Story describing the problem.

Also since user stories are new, lets leave link for how to write them? Like we do with Loom

2019-09-06 14:37 UTC, musangowope submitted a review, later dismissed

2019-09-06 16:46 UTC, robguy21 commented
```
---
name: Feature request
about: Suggest an idea for this project
title: "[FEATURE REQUEST] "
labels: ''
assignees: ''

---

## Description of Existing Problem
_What problem has led to the requirement of this feature request_

## User Story describing required solution
_A user story describing the feature to be implemented_

## Technical Description (not required initially)
_A technical description of the problem, this should be completed by the engineering manager or product manager_

## Additional Resources
_Add any context, screenshots, designs, links, etc. about the feature request here._

# VERSUS


## Problem Centric User Story
_A user story describing the feature to be implemented and the problem_

## Acceptance Criteria
_requirements for featured to be considered implemented_

## Technical Description (not required initially)
_A technical description of the problem, this should be completed by the engineering manager or product manager_

## Additional Resources
_Add any context, screenshots, designs, links, etc. about the feature request here._
```

2019-09-10 10:05 UTC, pruhesi commented
My vote is yes to the first one and yes to add acceptance criteria to the first one

2019-09-12 14:31 UTC, countnoobula commented
### User Story
**As a**: [Role]

**I want to**: [Brief description of feature from user perspective]

**Because**: [Brief reason for request of feature]

### Acceptance Criteria
_List of conditions that mark the story as complete_
- [ ] ...

### Edge cases
_List of edge cases to be considered when marking the story as complete_
- [ ] ...

2019-09-16 12:38 UTC, merged