Added State Machine Transition template
bonlineza/.github pull request #5
Opened 2019-09-25 15:04 UTC by robguy21

## Proposed changes

_Description of the changes implemented by this PR, feel free to be as verbose as needed_

...

## Types of changes

What type of changes does your code introduce?
_Put an `x` in the boxes that apply, leave blank if none_

- [ ] Frontend
- [ ] Backend
- [ ] Bugfix
- [ ] New feature
- [ ] Component of Major Release
- [ ] Project Management
- [ ] Quality of Life
- [ ] Test Improvements

## Checklist

_Put an `x` in the boxes that apply._

- [ ] Local Cypress Tests Pass with my changes (`yarn cypress:run`)
- [ ] Lint and unit tests pass locally with my changes (`yarn lint && ./vendor/bin/phpunit`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Dependant PRs

_List Pull Requests below in format `#<ISSUE-NUMBER>`_
- ...

## Relevant Issues

_List Issues below in format `#<ISSUE-NUMBER> [Full|Partial]`_
- ...

## Description

_If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc._

2019-09-25 15:09 UTC, willemwe0 submitted a review, later dismissed

2019-09-25 15:18 UTC, musangowope submitted a review, later dismissed

2019-09-25 15:24 UTC, adameier submitted a review, later dismissed

2019-09-25 15:28 UTC, countnoobula requested changes

2019-09-25 15:28 UTC, countnoobula commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Acceptance Criteria for On Entry Actions
I feel we should have `On Exit Actions`
Though, if we look at Assa, given that it's using the legacy system, it doesn't have access to the `On Entry` and `On Exit`, functionality, as everything is wrapped in a transition.

Perhaps we should add a section for `Accepted Criteria for Transition Actions` aswell?

2019-09-25 15:34 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Acceptance Criteria for On Entry Actions
As discussed- this won't be changed to accommodate ASSA, and "on Exit Actions" belong in their own issues since it would involve heavy duplication

2019-09-25 15:48 UTC, sscholle requested changes

2019-09-25 15:48 UTC, sscholle commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +**To state**: [Brief reason for request of feature]
'to state' is a weird heading where a reason of the feature is required

2019-09-25 15:48 UTC, sscholle commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +_List of on entry actions that the state is responsible for_
'on entry actions' is quite vague...

2019-09-25 16:01 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +**To state**: [Brief reason for request of feature]
Updated descriptions

2019-09-25 16:01 UTC, countnoobula approved these changes

2019-09-25 16:01 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +_List of on entry actions that the state is responsible for_
this makes a lot of sense in allianz since we use the `onEntry` hook of a state to do stuff, however, in bonlineza projects we do not use the async-state-machine or TypedStateMachine so I've reverted the wording to be more inline with ASSA

2019-09-25 16:01 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Acceptance Criteria for On Entry Actions
see https://github.com/bonlineza/.github/pull/5#discussion_r328208725

2019-09-25 16:02 UTC, pruhesi commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Machine Story
This machine story section is pretty confusing to me 
in addition to what @sscholle mentioned about the headings and description of what should go there
An example might help me understand how this is gonna be used
Doesnt need to be in the template but maybe in the pr description

2019-09-25 16:03 UTC, sscholle approved these changes

2019-09-25 16:06 UTC, adameier approved these changes

2019-09-25 16:10 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Machine Story
I've updated the PR description with an example

2019-09-25 16:12 UTC, musangowope approved these changes

2019-09-26 07:49 UTC, pruhesi commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Machine Story
In the example what is `pass`. A button? an action?
``I can transition with: pass``

2019-09-26 08:38 UTC, robguy21 commented on .github/ISSUE_TEMPLATE/state_machine_transition.md
> +## Machine Story
it's a transition

2019-09-26 12:04 UTC, pruhesi approved these changes

2019-09-26 12:39 UTC, merged